#! /usr/bin/guile -s
!#

;; Bootstrap the game.
(add-to-load-path "./module")
(use-modules (gshmup core)
             (system repl server))

;; REPL for connecting to the game from Emacs
(spawn-server)

;; This loads the game configuration file when the engine is ready.
(add-hook! game-init-hook
           (lambda () (use-modules (gshmup init))))

(gshmup-start)
